name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  E-Addict-e2e:

    runs-on: ubuntu-latest

    strategy:
      # run test in different browsers using matrix
      matrix:
        test-version: ["chromium", "firefox", "webkit"]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'npm'

    - name: Get installed Playwright version
      id: playwright-version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
    
    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
    - run: npm ci
    - run: npx playwright install --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - run: npx playwright install-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      
    - run: npx playwright install-deps webkit
      if: ${{ matrix.test-version== 'webkit' && steps.playwright-cache.outputs.cache-hit == 'true' }}
    
    - run: npm run build --if-present
    - run: nohup node index.js &
    - run: npm run test-${{matrix.test-version}}
    
      env:
        FORCE_COLOR: 2
